# -*- coding: utf-8 -*-
"""REVE Tutorial - EEGMAT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wMytamrucmU9c2OIc-TcoEIj6xSqPGo

# Using REVE to classify EEG

In this tutorial, we train a classification head on the REVE model to demonstrate how it can be used as a powerfull off-the-shelf feature extractor.

## Loading REVE

To load the REVE model, go to the [Hugging Face collection](https://huggingface.co/collections/brain-bzh/reve) and select your model size (e.g. base).

The model is gated so you need to accept the terms of the form on the website. In general, you will need to authenticate before using the model. You can do this in the CLI here :
"""

from transformers import AutoModel
import torch

# %%
# Твой токен от HuggingFace
my_token = "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"

# Загружаем саму модель
model = AutoModel.from_pretrained(
    "brain-bzh/reve-base", 
    trust_remote_code=True, 
    token=my_token
)

pos_bank = AutoModel.from_pretrained(
    "brain-bzh/reve-positions", 
    trust_remote_code=True, 
    token=my_token
)

# Show all pre-registered positions
print(pos_bank.get_all_positions())

# Inspect the model
print(model)

# %%
"""At this stage, the last layer of the model is `Identity()`, we will replace it with a classifier layer suited for our case.
The dataset has 20 channels, and samples of 5s. The model output will be of size `[B, 20, 5, D]`, with `B` the batch size and `D` the hidden dimension (512 for the base model). We thus set the final layer to be of size `20*5*D`.
"""

dim = 62 * 4 * 512

model.final_layer = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.RMSNorm(dim),
    torch.nn.Dropout(0.1),
    torch.nn.Linear(dim, 2),
)

# %%
import mne

# RL hand imageries: 4, 8, 12
runs = ['04', '08', '12']
raws = []

for r in runs:
    fpath = f'REVE_aos/MNE-eegbci-data/files/eegmmidb/1.0.0/S001/S001R{r}.edf'
    raw_tmp = mne.io.read_raw_edf(fpath, preload=True, verbose=False)
    raws.append(raw_tmp)

# Склеиваем все 3 записи в одну
raw = mne.concatenate_raws(raws)

# Ресемплим объединенный файл
raw.resample(200)

ch_names = [ch.replace('.', '').strip().upper() for ch in raw.ch_names]

valid_positions = set(pos_bank.position_names)
channels_to_drop = [
    orig_ch for orig_ch, clean_ch in zip(raw.ch_names, ch_names)
    if clean_ch not in valid_positions
]

raw_filtered = raw.copy().drop_channels(channels_to_drop)
ch_names = [ch.replace('.', '').strip().upper() for ch in raw_filtered.ch_names]

# %%
"""NB: in practice, when using REVE on your tasks, you will only need to load it from Huggingface and modify the last layer.

## Training scripts

You can adjust some of the training parameters here.
"""
# Training parameters
batch_size = 64
n_epochs = 20
lr = 1e-3

positions = pos_bank(ch_names)

# %% Блок 4: Подготовка датасета (заменяем HF dataset на кастомный PyTorch Dataset)
from torch.utils.data import Dataset, DataLoader, random_split
import numpy as np

class PhysioNet2ClassDataset(Dataset):
    def __init__(self, raw_mne, duration=4.0):
        # Извлекаем события из файла
        events, event_dict = mne.events_from_annotations(raw_mne, verbose=False)
        
        # Нам нужны только воображаемые движения левой (T1) и правой (T2) рукой
        mapping = {'T1': event_dict['T1'], 'T2': event_dict['T2']}
        
        # Задаем окно так, чтобы получилось ровно 800 отсчетов (4.0 сек * 200 Гц)
        tmax = duration - (1 / raw_mne.info['sfreq']) 
        
        epochs = mne.Epochs(
            raw_mne, events, event_id=mapping, 
            tmin=0, tmax=tmax, baseline=None, preload=True, verbose=False
        )
        
        self.data = torch.tensor(epochs.get_data(copy=True), dtype=torch.float32)
        
        # Переводим оригинальные ID событий в метки классов 0 и 1
        raw_labels = epochs.events[:, -1]
        self.labels = torch.tensor([0 if l == mapping['T1'] else 1 for l in raw_labels], dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        # Туториал ожидает, что батч будет словарем с ключами 'data' и 'labels'
        return {"data": self.data[idx], "labels": self.labels[idx]}

dataset = PhysioNet2ClassDataset(raw_filtered)
print(f"Всего примеров в файле: {len(dataset)}")

# Поскольку в одном файле PhysioNet очень мало эпох (обычно около 30),
# мы переопределяем твой batch_size=64 на 8, чтобы было несколько шагов (steps) в эпохе
batch_size = 8  

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

# %% Блок 5: Функции обучения и оценки (скопировано из туториала REVE)
from sklearn.metrics import accuracy_score, balanced_accuracy_score, cohen_kappa_score, f1_score, roc_auc_score, average_precision_score

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
positions = positions.to(device)

def train_one_epoch(model, optimizer, dataloader):
    model.train()
    for batch in dataloader:
        optimizer.zero_grad()
        
        # Разворачиваем тензор позиций под размер текущего батча
        B = batch["data"].shape[0]
        batch_pos = positions.unsqueeze(0).expand(B, -1, -1)
        
        out = model(batch["data"].to(device), batch_pos)
        loss = criterion(out, batch["labels"].to(device))
        
        loss.backward()
        optimizer.step()

def eval_model(model, dataloader):
    model.eval()
    all_preds, all_labels, all_probs = [], [], []
    
    with torch.no_grad():
        for batch in dataloader:
            B = batch["data"].shape[0]
            batch_pos = positions.unsqueeze(0).expand(B, -1, -1)
            
            out = model(batch["data"].to(device), batch_pos)
            
            probs = torch.softmax(out, dim=1)
            preds = torch.argmax(out, dim=1)
            
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch["labels"].numpy())
            all_probs.extend(probs.cpu().numpy())
            
    gt = np.array(all_labels)
    pr = np.array(all_preds)
    pr_probs = np.array(all_probs)

    acc = accuracy_score(gt, pr)
    balanced_acc = balanced_accuracy_score(gt, pr)
    cohen_kappa = cohen_kappa_score(gt, pr)
    f1 = f1_score(gt, pr, average="weighted")
    
    # Обработка исключения на случай, если в валидационный батч попал только 1 класс
    try:
        auroc = roc_auc_score(gt, pr_probs[:, 1])
        auc_pr = average_precision_score(gt, pr_probs[:, 1])
    except ValueError:
        auroc, auc_pr = 0.0, 0.0

    return acc, balanced_acc, cohen_kappa, f1, auroc, auc_pr

# %% Блок 6: Главный цикл обучения (как в туториале)

# Замораживаем backbone, обучаем только классификационную "голову"
for param in model.parameters():
    param.requires_grad = False
for param in model.final_layer.parameters():
    param.requires_grad = True

optimizer = torch.optim.AdamW(model.final_layer.parameters(), lr=lr)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max", factor=0.5, patience=3)
criterion = torch.nn.CrossEntropyLoss()

best_val_acc = 0
best_final_layer = None

for epoch in range(n_epochs):
    print(f"Epoch {epoch + 1}/{n_epochs}")
    
    train_one_epoch(model, optimizer, train_loader)
    
    _, b_acc, _, _, auroc, auc_pr = eval_model(model, val_loader)
    
    scheduler.step(b_acc)
    
    if b_acc > best_val_acc:
        best_val_acc = b_acc
        best_final_layer = model.final_layer.state_dict()
        
    print(f"Validation balanced accuracy: {b_acc:.4f} | AUROC: {auroc:.4f}")

# Загружаем лучшую модель по итогам валидации
if best_final_layer is not None:
    model.final_layer.load_state_dict(best_final_layer)
    print(f"Training complete. Best Validation Balanced Accuracy: {best_val_acc:.4f}")

# %%
